server:
  port: ${PORT}
  address: 0.0.0.0

lavalink:
  server:
    password: "${LAVALINK_SERVER_PASSWORD}"
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      nico: true
      http: true
      local: false

logging:
  level:
    root: INFO
    lavalink: INFO
